// Names drawn from Dark Souls III — NPCs, lords, knights, and locations.
// The app's own name is a DS3 reference (Gwyn's nameless firstborn), so
// project defaults lean into the lore. Single words only, no honorifics.
const DS3_NAMES = [
  "Lothric",
  "Lorian",
  "Anri",
  "Horace",
  "Yuria",
  "Yoel",
  "Karla",
  "Cornyx",
  "Irina",
  "Eygon",
  "Orbeck",
  "Hawkwood",
  "Andre",
  "Emma",
  "Ludleth",
  "Greirat",
  "Patches",
  "Siegward",
  "Sirris",
  "Leonhard",
  "Friede",
  "Gael",
  "Lapp",
  "Vordt",
  "Aldrich",
  "Sulyvahn",
  "Yhorm",
  "Oceiros",
  "Gundyr",
  "Wolnir",
  "Midir",
  "Filianore",
  "Velka",
  "Yorshka",
  "Ariandel",
  "Astora",
  "Catarina",
  "Carim",
  "Mirrah",
  "Irithyll",
  "Vinheim",
  "Berenike",
  "Forossa",
  "Pontiff",
  "Halflight",
  "Kriemhild",
];

export function randomProjectName(): string {
  return DS3_NAMES[Math.floor(Math.random() * DS3_NAMES.length)];
}
